### ISSUE TITLE
Some CSS doesn't apply to html on account settings page

### ISSUE THREAD

**Issue by stephanerbn** [stephanyan/soundbase#10]
Piece of CSS I want to apply on account.php file:

```css
#wrapper-settings {
  background-image: url("../vendor/images/accountpage/background.jpg");
  height: 400px;
}

.delete-button a {
  color: #fff;
  text-decoration: none;
}
```

```html
<div class="wrapper" id="wrapper-settings">
      <h1>PARAMÈTRE DU COMPTE</h1>
      <h2>MODIFIEZ OU SUPPRIMEZ VOTRE COMPTE</h2>
</div>

<button type="button" class="btn btn-danger delete-button">
        <a href="script/deleteAccount.php">Supprimer mon compte</a>
</button>
```
